# Generated by Django 3.1 on 2021-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
