# Generated by Django 3.1 on 2021-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopify', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
