# Generated by Django 3.1 on 2021-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopify', '0007_auto_20210501_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
