# Generated by Django 3.1 on 2021-05-05 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshopify', '0008_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productreview',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopify.customer')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshopify.productreview')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopify.product')),
            ],
        ),
    ]
